### PR TITLE
Address and fix `golangci-lint` issues

### LINKED ISSUE #86: [DEV] Address issues from `golangci-lint` without breaking features
**Short Description**
When running `golangci-lint` or `make lint` in the repo, we get a lot of linting-related errors especially for not checking errors. This task is mainly for code quality purposes and should be completed *without breaking any features* and is relatively lowerish priority.

**Definition of Done**
This development task is complete when all of the `golangci-lint` errors are address for the current `main` branch.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by davidallendj**
Address #86 by fixing all of the issues produced with `golangci-lint run`. This can be tested by running `magellan` like normal by following the README.

### CODE REVIEW

File: cmd/collect.go [hunk 1]
```diff
@@ -157,7 +160,7 @@ func init() {
 	CollectCmd.Flags().StringVarP(&idMap, "bmc-id-map", "m", "", "Set the BMC ID mapping from raw json data or use @<path> to specify a file path (json or yaml input)")
 
 	CollectCmd.MarkFlagsMutuallyExclusive("output-file", "output-dir")
-	CollectCmd.RegisterFlagCompletionFunc("format", completionFormatData)
+	_ = CollectCmd.RegisterFlagCompletionFunc("format", completionFormatData)
```
Comment (synackd) [inline cmd/collect.go:163]: Any time we ignore an error, we should comment why we are ignoring it.

File: cmd/crawl.go [hunk 2]
```diff
@@ -153,7 +153,7 @@ func init() {
 	CrawlCmd.Flags().BoolVar(&showOutput, "show", false, "Show the output of a collect run")
 	CrawlCmd.Flags().VarP(&crawlOutputFormat, "format", "F", "Set the output format (json|yaml)")
 
-	CrawlCmd.RegisterFlagCompletionFunc("format", completionFormatData)
+	_ = CrawlCmd.RegisterFlagCompletionFunc("format", completionFormatData)
```
Comment (synackd) [inline cmd/crawl.go:156]: See comment above regarding ignoring errors.

File: cmd/list.go [hunk 3]
```diff
@@ -53,7 +54,7 @@ func init() {
 	ListCmd.Flags().VarP(&listOutputFormat, "format", "F", "Set the output format (list|json|yaml)")
 	ListCmd.Flags().BoolVar(&showCache, "cache-info", false, "Show cache information and exit")
 
-	ListCmd.RegisterFlagCompletionFunc("format", completionFormatData)
+	_ = ListCmd.RegisterFlagCompletionFunc("format", completionFormatData)
```
Comment (synackd) [inline cmd/list.go:57]: See comment above regarding ignoring errors.

File: cmd/power.go [hunk 4]
```diff
@@ -247,7 +250,7 @@ func init() {
 	PowerCmd.Flags().String("cacert", "", "Set the path to CA cert file (defaults to system CAs when blank)")
 	PowerCmd.Flags().VarP(&powerFormat, "format", "F", "Set the output format (json|yaml)")
 
-	PowerCmd.RegisterFlagCompletionFunc("format", completionFormatData)
+	_ = PowerCmd.RegisterFlagCompletionFunc("format", completionFormatData)
```
Comment (synackd) [inline cmd/power.go:253]: See comment above regarding ignoring errors.

File: cmd/send.go [hunk 5]
```diff
@@ -128,7 +128,7 @@ func init() {
 	sendCmd.Flags().BoolVarP(&forceUpdate, "force-update", "f", false, "Set flag to force update data sent to SMD")
 	sendCmd.Flags().StringVar(&cacertPath, "cacert", "", "Set the path to CA cert file (defaults to system CAs when blank)")
 
-	sendCmd.RegisterFlagCompletionFunc("format", completionFormatData)
+	_ = sendCmd.RegisterFlagCompletionFunc("format", completionFormatData)
```
Comment (synackd) [inline cmd/send.go:131]: See comment above regarding ignoring errors.

File: pkg/secrets/encryption.go [hunk 6]
```diff
@@ -16,8 +16,8 @@ import (
 func deriveAESKey(masterKey []byte, secretID string) []byte {
 	salt := []byte(secretID)
 	hkdf := hkdf.New(sha256.New, masterKey, salt, nil)
-	derivedKey := make([]byte, 32) // AES-256 key
-	io.ReadFull(hkdf, derivedKey)
+	derivedKey := make([]byte, 32)       // AES-256 key
+	_, _ = io.ReadFull(hkdf, derivedKey) // no need to check err here
```
Comment (synackd) [inline pkg/secrets/encryption.go:20]: Can we add to this comment why we don't need to check error here?

File: internal/login.go [hunk 7]
```diff
@@ -46,7 +46,7 @@ func Login(loginUrl string, targetHost string, targetPort int) (string, error) {
 	r.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
 		// try and extract access token from headers
 		accessToken = r.Header.Get("access_token")
-		s.Close()
+		_ = s.Close()
```
Comment (synackd) [inline internal/login.go:49]: Even though it's idiomatic to ignore errors on close, it might be good to log a warning if it fails.

File: pkg/secrets/localstore_test.go [hunk 8]
```diff
@@ -27,6 +28,10 @@ func TestNewLocalSecretStore(t *testing.T) {
 	if hex.EncodeToString(store.masterKey) != masterKey {
 		t.Errorf("Expected master key %s, got %s", masterKey, hex.EncodeToString(store.masterKey))
 	}
+
+	if err = os.Remove(filename); err != nil {
+		log.Warn().Err(err).Msg("could not close response resource")
+	}
```
Comment (synackd) [inline pkg/secrets/localstore_test.go:34]: Instead of removing the `defer` and putting this at the end of the function, could we:
```go
defer func() {
    if err = os.Remove(filename); err != nil {
		log.Warn().Err(err).Msg("could not close response resource")
	}
}
```
instead?

File: pkg/secrets/localstore_test.go [hunk 9]
```diff
@@ -70,6 +74,10 @@ func TestStoreAndGetSecretByID(t *testing.T) {
 	if retrievedSecret != secretValue {
 		t.Errorf("Expected secret value %s, got %s", secretValue, retrievedSecret)
 	}
+
+	if err = os.Remove(filename); err != nil {
+		log.Warn().Err(err).Msg("could not close response resource")
+	}
```
Comment (synackd) [inline pkg/secrets/localstore_test.go:80]: See `defer` comment above.

File: pkg/secrets/localstore_test.go [hunk 10]
```diff
@@ -101,6 +108,9 @@ func TestStoreAndGetSecretJSON(t *testing.T) {
 	if retrieved != jsonSecret {
 		t.Errorf("Expected %s, got %s", jsonSecret, retrieved)
 	}
+	if err = os.Remove(filename); err != nil {
+		log.Warn().Err(err).Msg("could not close response resource")
+	}
```
Comment (synackd) [inline pkg/secrets/localstore_test.go:113]: See `defer` comment above.

**Review by synackd — COMMENTED** [review]
Looks good, just some error-handling and `defer` things mentioned in the review.

File: pkg/secrets/localstore_test.go (hunk 8 above)
Comment (davidallendj) [reply pkg/secrets/localstore_test.go:34]: That's a good idea. I wasn't quite sure how to handle these, but I think this way will work.

**Review by synackd — APPROVED** [review]
LGTM
