### PR TITLE
fix #36 and provide better error handling

### LINKED ISSUE #36: Running the `crawl` subcommand without arguments causes a crash:
Running the `crawl` subcommand without arguments causes a crash:
```
# ./magellan crawl 
{"level":"error","error":"endpoint must starts with http or https","time":"2024-07-01T14:21:53Z","message":"failed to connect to BMC"}
panic: endpoint must starts with http or https

goroutine 1 [running]:
github.com/OpenCHAMI/magellan/cmd.glob..func2(0xc0001fe400?, {0xccfac6?, 0x4?, 0xccfaca?})
	/opt/shared/magellan/cmd/crawl.go:22 +0x29f
github.com/spf13/cobra.(*Command).execute(0x14a5fe0, {0x15191a0, 0x0, 0x0})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x14a6b60)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/OpenCHAMI/magellan/cmd.Execute()
	/opt/shared/magellan/cmd/root.go:51 +0x1a
main.main()
	/opt/shared/magellan/main.go:8 +0xf
```
Perhaps it would be better to have the BMC URI be a positional argument rather than a flag.

_Originally posted by @synackd in https://github.com/OpenCHAMI/magellan/issues/34#issuecomment-2200301201_

### PR DESCRIPTION
**Pull request by alexlovelltroy**

### CODE REVIEW

File: cmd/crawl.go [hunk 1]
```diff
@@ -3,23 +3,36 @@ package cmd
...
+	"net/url"
 
 	"github.com/OpenCHAMI/magellan/pkg/crawler"
 	"github.com/spf13/cobra"
 )
 
 var crawlCmd = &cobra.Command{
-	Use:   "crawl",
+	Use:   "crawl [uri]",
 	Short: "Crawl a single BMC for inventory information",
```
Comment (synackd) [inline cmd/crawl.go:15]: Perhaps we could add a long description below this that describes what `uri` is. I don't think there is a standard way to do this in Cobra yet.

**Review by synackd — COMMENTED** [review]
I tested this a bit and didn't get any panics, just the expected error messages. I just added a small comment for adding a description of `uri` that may be helpful.

File: cmd/crawl.go (hunk 1 above)
Comment (davidallendj) [reply cmd/crawl.go:15]: I want to second this. I think we also want to include that `uri` is the host and not the Redfish root endpoint as mentioned in [the issue](https://github.com/OpenCHAMI/magellan/issues/36#issuecomment-2200932275).

**Comment by synackd** [comment]
If an extra slash is added, an authentication error occurs:

```
# ./magellan crawl -i -u <username> -p '<password>' https://bmc-te05/
{"level":"error","error":"authentication failed.  Check your username and password: https://bmc-te05/","time":"2024-07-02T20:23:54Z","message":"failed to connect to BMC"}
2024/07/02 20:23:54 Error crawling BMC: authentication failed.  Check your username and password: https://bmc-te05/
```
vs. no trailing slash:
```
# ./magellan crawl -i -u <username -p '<password>' https://bmc-te05
{"level":"info","time":"2024-07-02T20:26:53Z","message":"found 7 chassis in ServiceRoot"}
[...]
```
Adding URL sanitation should clear this up.

**Comment by synackd** [comment]
> If an extra slash is added, an authentication error occurs:
> 
> ```
> # ./magellan crawl -i -u <username> -p '<password>' https://bmc-te05/
> {"level":"error","error":"authentication failed.  Check your username and password: https://bmc-te05/","time":"2024-07-02T20:23:54Z","message":"failed to connect to BMC"}
> 2024/07/02 20:23:54 Error crawling BMC: authentication failed.  Check your username and password: https://bmc-te05/
> ```
> 
> vs. no trailing slash:
> 
> ```
> # ./magellan crawl -i -u <username -p '<password>' https://bmc-te05
> {"level":"info","time":"2024-07-02T20:26:53Z","message":"found 7 chassis in ServiceRoot"}
> [...]
> ```
> 
> Adding URL sanitation should clear this up.

resolved in [afe84f6](https://github.com/OpenCHAMI/magellan/pull/37/commits/afe84f6129348b493323d9fec429ad6c6c50584d)

File: cmd/crawl.go [hunk 2]
```diff
@@ -3,23 +3,43 @@ package cmd
...
+	"net/url"
+	"strings"
 
 	"github.com/OpenCHAMI/magellan/pkg/crawler"
 	"github.com/spf13/cobra"
 )
 
 var crawlCmd = &cobra.Command{
-	Use:   "crawl",
+	Use:   "crawl [uri] e.g. magellan crawl https://bmc.example.com",
```
Comment (synackd) [inline cmd/crawl.go:15]: I think it would be better to put this in a `Long`, since the way this is right now appends `[flags]` at the end of the example command line:
```
# ./magellan crawl --help
Crawl a single BMC for inventory information

Usage:
  magellan crawl [uri] e.g. magellan crawl https://bmc.example.com [flags]
```

If we did something like:

```diff
diff --git a/cmd/crawl.go b/cmd/crawl.go
index 84fb24e..ffc55f1 100644
--- a/cmd/crawl.go
+++ b/cmd/crawl.go
@@ -12,7 +12,11 @@ import (
 )
 
 var crawlCmd = &cobra.Command{
-       Use:   "crawl [uri] e.g. magellan crawl https://bmc.example.com",
+       Use:   "crawl [uri]",
+       Long:  "Crawl a single BMC for inventory information\n" +
+              "\n" +
+              "Example:\n" +
+              "  magellan crawl https://bmc.example.com",
        Short: "Crawl a single BMC for inventory information",
        Args: func(cmd *cobra.Command, args []string) error {
                // Validate that the only argument is a valid URI
```

We would get some nicer output:

```
# ./magellan crawl --help
Crawl a single BMC for inventory information

Example:
  magellan crawl https://bmc.example.com

Usage:
  magellan crawl [uri] [flags]
```

Comment (alexlovelltroy) [reply cmd/crawl.go]: done!

Comment (synackd) [reply cmd/crawl.go]: Looks good!

**Review by synackd — APPROVED** [review]
All of my requests have been satiated. LGTM!
